# 💾 Carga de Archivos con pandas

Cuando analizamos datos en Python, una práctica común y poderosa es **cargar los datos (CSV, Excel, JSON, SQL, etc.) dentro de un DataFrame de Pandas**.  
Esto ofrece grandes ventajas frente a trabajar directamente con archivos o consultas SQL tradicionales.

---

## 🧩 1️⃣ Mayor Facilidad para Manipular y Analizar Datos

Pandas permite transformar, filtrar, agrupar y limpiar los datos **de forma directa e intuitiva**, con pocas líneas de código.

## ⚙️ Rendimiento y Velocidad en Pandas: El Poder del Trabajo en Memoria

Una de las principales ventajas de **Pandas** frente a trabajar directamente con archivos o bases de datos SQL es su **velocidad de procesamiento**.  
Esto se debe a que **Pandas carga los datos completamente en memoria (RAM)**, lo que permite realizar operaciones de forma mucho más rápida que leerlos o consultarlos constantemente desde el disco.

---

### 🧠 ¿Por qué es más rápido?

Cuando trabajas con un archivo (por ejemplo, un CSV) o con una base de datos, cada vez que ejecutas una operación, el sistema debe:

1. **Leer desde el disco** (I/O, input/output).
2. **Buscar la información** necesaria.
3. **Cargar temporalmente** los datos para procesarlos.

➡️ Este proceso se repite **cada vez** que ejecutas una consulta o cálculo, lo que implica **acceso constante al disco** — una de las operaciones más lentas del sistema.

En cambio, con Pandas:

- Los datos se **cargan una sola vez** a la memoria RAM.
- Todas las transformaciones, filtros, agrupaciones y cálculos se realizan **directamente sobre la memoria**, sin volver a leer el archivo.
- Esto reduce drásticamente el tiempo de espera y permite trabajar de manera **interactiva e inmediata**.

---

In [2]:
import pandas as pd

In [1]:
!pwd

/content

In [3]:
!ls

harrypotter.json  libros.csv  sample_data

In [4]:
PATH_CSV = '/content/libros.csv'

# CARGAR ARCHIVOS CSV CON PANDAS

In [5]:
df_books = pd.read_csv(PATH_CSV)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

# CARGA DE ARCHIVO JSON

In [6]:
pd.read_json('/content/harrypotter.json')

,Name,Link,Descr,Gender,Species/Race,Blood,School,Profession
0,Mrs. Abbott,https://www.hp-lexicon.org/character/abbott-fa...,"Mrs. Abbott was the mother of Hannah Abbott, a...",Female,Witch,Muggle-born,Unknown,Unknown
1,Hannah Abbott,https://www.hp-lexicon.org/character/abbott-fa...,Hannah Abbott is a Hufflepuff student in Harry...,Female,Witch,Half-blood,Hogwarts - Hufflepuff,Landlady of the Leaky Cauldron
2,Abel Treetops,https://www.hp-lexicon.org/character/abel-tree...,Abel Treetops was a wizard from Cincinnati who...,Male,Wizard,Unknown,Unknown,Unknown
3,Euan Abercrombie,https://www.hp-lexicon.org/character/abercromb...,Euan Abercrombie was a small boy with prominen...,Male,Wizard,Unknown,Hogwarts - Gryffindor,Unknown
4,Aberforth Dumbledore,https://www.hp-lexicon.org/character/dumbledor...,"Aberforth Dumbledore was a tall, thin, grumpy-...",Male,Wizard,Half-blood,Hogwarts - Student,Barman
...,...,...,...,...,...,...,...,...
1935,Georgi Zdravko,https://www.hp-lexicon.org/character/georgi-zd...,Georgi Zdravko played Keeper for the Bulgarian...,Male,Wizard,Unknown,Unknown,Quidditch player (Seeker)
1936,Zograf,https://www.hp-lexicon.org/character/zograf/,Zograf played Keeper for the Bulgarian Nationa...,NaN,Wizard,Unknown,Unknown,Quidditch player (Keeper)
1937,Zonko,https://www.hp-lexicon.org/character/zonko/,Founder(?) of Zonko’s Joke Shop. Possibly a re...,NaN,Unknown,Unknown,Unknown,Unknown
1938,Valentina Vázquez,https://www.hp-lexicon.org/character/valentina...,Valentina Vázquez was President of the Argenti...,Female,Witch,Unknown,Unknown,President of the Argentinian Council of Magic
1939,Zygmunt Budge,https://www.hp-lexicon.org/character/zygmunt-b...,Zygmunt Budge is considered to be one of the m...,Male,Wizard,Unknown,Hogwarts - Student,"Potions Master, Potioneer, Inventor, Author"

In [7]:
pd.read_csv('/content/drive/MyDrive/CODIGOG6/MODULO3/PANDAS/libros.csv')

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction