#DATASET : https://www.kaggle.com/datasets/mohamedasak/imdb-top-250-movies?resource=download

In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('/content/imdb_top_movies.csv')
df_movies.head(5)

,Rank,Title,Year,Rating,Duration,Certificate,Genres,Description,Image URL,Movie URL
0,1,The Shawshank Redemption,1994,9.3,2h 22m,R,Drama,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,https://www.imdb.com/title/tt0111161/
1,2,The Godfather,1972,9.2,2h 55m,R,"Crime, Drama",The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BNGEwYj...,https://www.imdb.com/title/tt0068646/
2,3,The Dark Knight,2008,9.1,2h 32m,PG-13,"Action, Crime, Drama",When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://www.imdb.com/title/tt0468569/
3,4,The Godfather Part II,1974,9.0,3h 22m,R,"Crime, Drama",The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BMDIxMz...,https://www.imdb.com/title/tt0071562/
4,5,12 Angry Men,1957,9.0,1h 36m,Approved,"Crime, Drama",The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BYjE4Nz...,https://www.imdb.com/title/tt0050083/

### Ejercicio 1: Filtrado de datos 🔍

1. Filtra todas las películas que tengan:
   - Un rating mayor o igual a 9.0
   - Y que sean del año 2000 en adelante

2. Del resultado, muestra solamente estas columnas:
   - `Rank`, `Title`, `Year`, `Rating`, `Certificate`, `Genres`

3. Ordena el resultado por `Rating` (descendente) y luego por `Year` (descendente).

In [3]:
df_movies[
    (df_movies['Rating'] >= 9.0) &
    (df_movies['Year'] >= 2000)
]

,Rank,Title,Year,Rating,Duration,Certificate,Genres,Description,Image URL,Movie URL
2,3,The Dark Knight,2008,9.1,2h 32m,PG-13,"Action, Crime, Drama",When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://www.imdb.com/title/tt0468569/
5,6,The Lord of the Rings: The Return of the King,2003,9.0,3h 21m,PG-13,"Adventure, Drama, Fantasy",Gandalf and Aragorn lead the World of Men agai...,https://m.media-amazon.com/images/M/MV5BMTZkMj...,https://www.imdb.com/title/tt0167260/

In [4]:
cols = ['Rank','Title','Year','Rating','Certificate','Genres']
df_movies[
    (df_movies['Rating'] >= 9.0) &
    (df_movies['Year'] >= 2000)
][cols]

,Rank,Title,Year,Rating,Certificate,Genres
2,3,The Dark Knight,2008,9.1,PG-13,"Action, Crime, Drama"
5,6,The Lord of the Rings: The Return of the King,2003,9.0,PG-13,"Adventure, Drama, Fantasy"

In [5]:
df_movies[
    (df_movies['Rating'] >= 9.0) &
    (df_movies['Year'] >= 2000)
][cols].sort_values(by=['Rating','Year'],ascending=[False,False])

,Rank,Title,Year,Rating,Certificate,Genres
2,3,The Dark Knight,2008,9.1,PG-13,"Action, Crime, Drama"
5,6,The Lord of the Rings: The Return of the King,2003,9.0,PG-13,"Adventure, Drama, Fantasy"

### Ejercicio 2: Agrupaciones 📊

1. Agrupa las películas por año (`Year`) y calcula:
   - El número de películas por año.
   - El rating promedio por año.

2. Ordena el resultado de mayor a menor rating promedio.

3. Muestra solo las primeras 10 filas del resultado final.